Name: product.rpc
ListenOn: 0.0.0.0:9001

Etcd:
  Hosts:
    - host.docker.internal:2379
  Key: product.rpc

Mysql:
  DataSource: root:123456@tcp(host.docker.internal:3306)/mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
  - Host: redis:6379
    Type: node
    Pass:

Prometheus:
  Host: 0.0.0.0
  Port: 9091
  Path: /metrics

Telemetry:
  Name: product.rpc
  Endpoint: http://jaeger:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger