// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 记录不存在
func IsRecordNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_RecordNotFound.String() && e.Code == 404
}

// 记录不存在
func ErrorRecordNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_RecordNotFound.String(), fmt.Sprintf(format, args...))
}

// 重复注册
func IsRuplicationRegister(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_RuplicationRegister.String() && e.Code == 405
}

// 重复注册
func ErrorRuplicationRegister(format string, args ...interface{}) *errors.Error {
	return errors.New(405, ErrorReason_RuplicationRegister.String(), fmt.Sprintf(format, args...))
}
